# Generated by Django 2.1.5 on 2019-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sh',
            field=models.BooleanField(default=False),
        ),
    ]
