# Generated by Django 2.1.5 on 2019-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_photo_sh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
