# Generated by Django 2.1.5 on 2019-02-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0003_auto_20190210_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='sh',
            new_name='sharing',
        ),
    ]
